######################################################################
# Automatically generated by qmake (2.01a) Di. Mär 17 20:54:26 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
              src/lib \
              src/test \
INCLUDEPATH += . src/lib

# Input
HEADERS += src/lib/ringbuffer.h
SOURCES += src/lib/ringbuffer.cpp \
	src/test/test_seq.cpp
