######################################################################
# Automatically generated by qmake (2.01a) Di. M�r 17 20:54:26 2015
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . \
	src/lib \
	src/test \
INCLUDEPATH += . include

# Input
HEADERS += include/ringbuffer/ringbuffer.h
SOURCES += src/lib/ringbuffer.cpp \
	src/test/test_seq.cpp \
	src/test/test_par.cpp

OTHER_FILES += src/lib/CMakeLists.txt \
	src/test/CMakeLists.txt \
	src/CMakeLists.txt \
	src/ringbuffer.pc.in \
	CMakeLists.txt \
	src/config.h.in
